// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIRDpd6lWLyT9pp__Kf9IkgoXBAA1wu5M',
    appId: '1:199432855141:web:fe7fab47c14c7b5f5fb08c',
    messagingSenderId: '199432855141',
    projectId: 'olyinfo',
    authDomain: 'olyinfo.firebaseapp.com',
    storageBucket: 'olyinfo.appspot.com',
    measurementId: 'G-VPNLSN2YEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Kzb8TSvjOZuycqd6dvdpeDJ7ThsvfwA',
    appId: '1:199432855141:android:30034bcbd5467e065fb08c',
    messagingSenderId: '199432855141',
    projectId: 'olyinfo',
    storageBucket: 'olyinfo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl_r8kI1QB3nDCzYvUS9ovzD3QQFIW7M8',
    appId: '1:199432855141:ios:f2361ff72a3908125fb08c',
    messagingSenderId: '199432855141',
    projectId: 'olyinfo',
    storageBucket: 'olyinfo.appspot.com',
    iosClientId: '199432855141-qe8bv0i6rkn00c93a7kpaonl2aqpauqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.olyinfo',
  );
}
